# Generated by Django 2.2.13 on 2020-11-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0002_auto_20201030_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('repo_full_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full', models.TextField()),
            ],
        ),
    ]
